version: "3.9"

services:

  # ----------------------------
  # PostgreSQL for Healenium
  # ----------------------------
  postgres-db:
    image: postgres:15.5-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
    networks:
      - healenium

  # ----------------------------
  # Healenium Backend
  # ----------------------------
  healenium:
    image: healenium/hlm-backend:3.4.6
    container_name: healenium
    restart: on-failure
    ports:
      - "7878:7878"
    links:
      - postgres-db
    environment:
      - SPRING_POSTGRES_DB=healenium
      - SPRING_POSTGRES_SCHEMA=healenium
      - SPRING_POSTGRES_USER=healenium_user
      - SPRING_POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
      - SPRING_POSTGRES_DB_HOST=postgres-db
      - KEY_SELECTOR_URL=false
      - COLLECT_METRICS=true
      - HLM_LOG_LEVEL=info
    volumes:
      - ./screenshots/:/screenshots
      - ./logs/:/logs
    networks:
      - healenium

  # ----------------------------
  # Healenium Selector-Imitator
  # ----------------------------
  selector-imitator:
    image: healenium/hlm-selector-imitator:1.4
    container_name: selector-imitator
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - healenium

  # ----------------------------
  # Selenoid
  # ----------------------------
  selenoid:
    image: aerokube/selenoid:latest
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - healenium
    volumes:
      - "./selenoid-config:/etc/selenoid"
      - "./target:/output"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./target:/opt/selenoid/video"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/target
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-container-network", "healenium", "-limit", "15"]

  # ----------------------------
  # Selenoid UI
  # ----------------------------
  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    container_name: selenoid-ui
    networks:
      - healenium
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    restart: unless-stopped

networks:
  healenium:
    name: healenium
